# Generated by Django 4.1.1 on 2022-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Repos',
            field=models.IntegerField(),
        ),
    ]
