# Generated by Django 4.1.1 on 2022-09-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_users_repos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='UserName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Email',
        ),
    ]
